---
name: Build
on:
  push:
    branches-ignore:
      - v[0-9]*.*

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Unit Tests
        run: make test
